export const PLATFORMS = {
  LINKEDIN: {
    id: 'LINKEDIN',
    name: 'LinkedIn',
    icon: 'in',
    color: '#0077b5',
    charLimit: 3000,
    supportsMultiAccount: true,
    accountTypes: ['PAGE'],
    mediaSupport: { image: true, video: true, maxImages: 9, maxVideoSizeMB: 200 },
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api',
  },
  FACEBOOK: {
    id: 'FACEBOOK',
    name: 'Facebook',
    icon: 'f',
    color: '#1877f2',
    charLimit: 63206,
    supportsMultiAccount: true,
    accountTypes: ['PAGE', 'GROUP'],
    mediaSupport: { image: true, video: true, maxImages: 10, maxVideoSizeMB: 1024 },
    docsUrl: 'https://developers.facebook.com/docs/pages/publishing',
  },
  INSTAGRAM: {
    id: 'INSTAGRAM',
    name: 'Instagram',
    icon: '◈',
    color: '#e1306c',
    charLimit: 2200,
    supportsMultiAccount: false,
    accountTypes: ['PERSONAL'],
    mediaSupport: { image: true, video: true, maxImages: 10, maxVideoSizeMB: 100 },
    docsUrl: 'https://developers.facebook.com/docs/instagram-api/guides/content-publishing',
  },
  TWITTER: {
    id: 'TWITTER',
    name: 'X (Twitter)',
    icon: 'X',
    color: '#000000',
    charLimit: 280,
    supportsMultiAccount: false,
    accountTypes: ['PERSONAL'],
    mediaSupport: { image: true, video: true, maxImages: 4, maxVideoSizeMB: 512 },
    note: 'Requires X Basic plan ($100/mo) for write access',
    docsUrl: 'https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets',
  },
  THREADS: {
    id: 'THREADS',
    name: 'Threads',
    icon: '@',
    color: '#101010',
    charLimit: 500,
    supportsMultiAccount: false,
    accountTypes: ['PERSONAL'],
    mediaSupport: { image: true, video: true, maxImages: 10, maxVideoSizeMB: 100 },
    docsUrl: 'https://developers.facebook.com/docs/threads',
  },
  BLUESKY: {
    id: 'BLUESKY',
    name: 'Bluesky',
    icon: '☁',
    color: '#0085ff',
    charLimit: 300,
    supportsMultiAccount: false,
    accountTypes: ['PERSONAL'],
    mediaSupport: { image: true, video: false, maxImages: 4, maxVideoSizeMB: 0 },
    docsUrl: 'https://docs.bsky.app/docs/api/com-atproto-repo-create-record',
  },
  PINTEREST: {
    id: 'PINTEREST',
    name: 'Pinterest',
    icon: 'P',
    color: '#e60023',
    charLimit: 500,
    supportsMultiAccount: false,
    accountTypes: ['BOARD'],
    mediaSupport: { image: true, video: true, maxImages: 1, maxVideoSizeMB: 2048 },
    docsUrl: 'https://developers.pinterest.com/docs/api/v5/pins-create',
  },
  TUMBLR: {
    id: 'TUMBLR',
    name: 'Tumblr',
    icon: 't',
    color: '#35465c',
    charLimit: 4096,
    supportsMultiAccount: true,
    accountTypes: ['BLOG'],
    mediaSupport: { image: true, video: false, maxImages: 10, maxVideoSizeMB: 0 },
    docsUrl: 'https://www.tumblr.com/docs/en/api/v2#posts--create-a-post-neue-post-format',
  },
} as const

export type Platform = typeof PLATFORMS[keyof typeof PLATFORMS] & { note?: string }
export type PlatformId = keyof typeof PLATFORMS
