import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
page.on('console', m => console.log('CONSOLE:', m.type(), m.text().slice(0, 140)))
page.on('requestfailed', r => console.log('FAILED:', r.url().slice(0, 100), r.failure()?.errorText))
await page.goto('http://localhost:3020/login', { waitUntil: 'networkidle', timeout: 30000 })
await page.waitForTimeout(3000)
const body = await page.evaluate(() => document.body.innerText.slice(0, 200))
console.log('BODY:', JSON.stringify(body))
await browser.close()
